backend:
  # Use netlify identity as backend
  # name: proxy
  name: git-gateway
  repo: rajibchisim/eleventy-site
  proxy_url: http://localhost:8081/api/v1
  branch: master

media_folder: "assets/uploads"
public_folder: "assets/public"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
publish_mode: editorial_workflow
collections:
  - label: Blog categories
    name: category
    folder: src/_data/categories/
    create: true
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Slug
        name: slug
        widget: string
        
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: true   
    identifier_field: title 
    fields:
      - { label: "Title", name: "title", widget: "title" }
      - { label: "Slug", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$','A slug can have no spaces or special characters']}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: Keywords, name: keywords, widget: categories, required: false }
      - { label: 'Category', name: 'category', required: false, multiple: true, widget: 'relation', collection: 'category', search_fields: ['title'], value_field: 'slug', display_fields: ['title']}
      
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Main Navigation"
        name: "items"
        file: "src/_data/navigation.yml"
        fields:
          - label: Nav Links
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            collapsed: false
            fields:
              - { label: Text, name: text, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: description, widget: string, required: false }
      - label: "About us (Eg. use in footer)"
        name: "aboutus"
        file: "src/_data/aboutus.yml"
        fields:
          - label: Title for section
            name: text
            widget: string
          - label: Paragraphs
            name: items
            widget: list
            collapsed: false
            fields:
              - { label: Text, name: text, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yml"
        fields:
          - { label: Company name, name: company, widget: string, required: false }
          - label: Address line
            name: address
            widget: list
            allow_add: true
            fields:
              - { label: "Address line", name: line, widget: string, required: false }
          - { label: Phone, name: phone, widget: string }
          - { label: Email, name: email, widget: string }
          - { label: Google map, name: gmap, widget: string }
          - label: Socials
            name: socials 
            widget: list
            allow_add: true
            fields:
              - { label: Platform, name: name, widget: select, options: ['facebook', twitter, 'linkedin'] }
              - { label: Url, name: url, widget: string }
              
  - label: Services
    name: services
    files: 
      - label: Edit/add Services
        name: items
        file: "src/_data/services.yml"
        fields:
          - name: items
            label: Services
            widget: list
            allow_add: true
            fields:
              - { label: Name, name: title, widget: string }
              - { label: Description, name: body, widget: string }
              - { label: FontAwesome Icon 4.7, name: icon, widget: string }
              
  - label: Hero Slider
    name: heroSlider
    files: 
      - label: Add/Edit Hero Slider
        name: items
        file: "src/_data/hero_slider.yml"
        editor:
          preview: false
        fields:
          - name: items
            widget: list
            allow_add: true
            fields:
              - { name: title, label: Title, widget: string }
              - { name: body, label: Body, widget: string }
              - { name: image, label: Image, widget: image }
              - name: links
                label: Links 
                widget: list
                allow_add: true
                required: false
                max: 2
                fields:
                  - { name: url, label: Url, widget: string, required: false }
                  - { name: text, label: Text, widget: string, required: false }
                  
  - label: Latest work
    name: latestWork
    files: 
      - label: Add/Edit Latest work
        name: items
        file: "src/_data/latest_work.yml"
        editor:
          preview: false
        fields:
          - name: items
            widget: list
            allow_add: true
            fields:
              - { name: title, label: Title, widget: string }
              - { name: body, label: Body, widget: string }
              - { name: image, label: Image, widget: image }
              
  - label: FAQ
    name: faq
    files: 
      - label: Add/Edit FAQ
        name: items
        file: "src/_data/faqs.yml"
        editor:
          preview: false
        fields:
          - name: items
            widget: list
            allow_add: true
            fields:
              - { name: que, label: Question, widget: string }
              - { name: ans, label: Answer, widget: string }
              
  - label: Testimonials
    name: testimonials
    files: 
      - label: Add/Edit Testimonials
        name: items
        file: "src/_data/testimonials.yml"
        editor:
          preview: false
        fields:
          - name: items
            widget: list
            allow_add: true
            fields:
              - { name: message, label: Message, widget: string }
              - { name: name, label: Name, widget: string }
              - { name: role, label: Role/Designation, widget: string }
              - { name: image, label: Profile image, widget: image, required: false }
            
