backend:
  # Use netlify identity as backend
  name: proxy
  repo: rajibchisim/eleventy-site
  proxy_url: http://localhost:8081/api/v1
  branch: master

media_folder: "assets"
public_folder: "assets"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: true   
    identifier_field: title 
    fields:
      - { label: "Title", name: "title", widget: "title" }
      - { label: "Slug", name: "slug", widget: "slug", default: "{{title}}"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { name: categories, label: Categories, widget: categories}
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Main Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Links
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Phone, name: phone, widget: string }
          - { label: Email, name: email, widget: string }
          - { label: Address, name: address, widget: string }
          - { label: Google map, name: gmap, widget: string }
          - label: Socials
            name: socials 
            widget: list
            allow_add: true
            fields:
              - { label: Platform, name: name, widget: select, options: ['facebook', twitter, 'linkedin'] }
              - { label: Url, name: url, widget: string }
  - label: Services
    name: services
    files: 
      - label: Edit/add Services
        name: items
        file: "src/_data/services.yaml"
        fields:
          - name: items
            label: Services
            widget: list
            allow_add: true
            fields:
              - { label: Name, name: title, widget: string }
              - { label: Description, name: body, widget: string }
              - { label: FontAwesome Icon 4.7, name: icon, widget: string }
